name: Shell commands
on:
  push:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: echo a string
        run: echo "Hello world"

      - name: multiline script
        run: |
          python3 -V
          touch my_file_with_workflow.py
          ls -l
